apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-service
data:
  prometheus.yaml: 
     global:
       scrape_interval: 15s

     scrape_configs:
       - job_name: 'prometheus'
         static_configs:
           - targets: ['prometheus.default.svc.cluster.local:9090']

       - job_name: 'node-redis'
         static_configs:
           - targets: ['node-redis.default.svc.cluster.local:8080']

       - job_name: 'db-redis-rami'
         static_configs:
           - targets: ['db-redis-rami.default.svc.cluster.local:6379']    
